name: Deploy to Server

on:
  push:
    branches:
      - main  # Ganti 'main' dengan branch yang Anda inginkan

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install sshpass
        run: |
          sudo apt-get update
          sudo apt-get install -y sshpass

      - name: Deploy to server
        run: |
          sshpass -p "${{ secrets.SERVER_PASSWORD }}" ssh -vvv -o StrictHostKeyChecking=no -o IdentitiesOnly=yes ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_IP }} "
            ls -la &&
            cd /home/sga-cakrawala/htdocs/cakfest-landing-page &&
            rm -rf node_modules &&
            rm -rf dist &&
            nvm use 22 &&
            git checkout main &&
            git pull &&
            npm install &&
            npm run build &&
            rm -rf /home/sga-cakrawala/.pm2/logs/cakfest-landing-page-error.log &&
            rm -rf /home/sga-cakrawala/.pm2/logs/cakfest-landing-page-out.log &&
            pm2 stop cakfest-landing-page &&
            pm2 del cakfest-landing-page &&
            pm2 save &&
            npm run pm2:preview &&
            pm2 save # save again
          "